#!/usr/bin/env bash
# This script gives information about a file

if [[ -e "school"  &&  -s "school" ]]; then
	echo school file exists
	echo school file is not empty
	if [ -f "school" ]; then
		echo school is a regular file
	fi
elif [[ -e "school"  &&  ! -s "school" ]]; then
	echo school file exists
	echo school file is empty
	if [ -f "school" ]; then
		echo school is a regular file
	fi
else
	echo school file does not exist
fi
